export function createAtmosphere(T,scene,sun,world){
 let clock=17.5,cycle=true;
 const sky=new T.Mesh(new T.SphereGeometry(1800,32,20),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{day:{value:1},time:{value:0},sunDir:{value:new T.Vector3(0,1,0)}},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 v;uniform float day;uniform float time;uniform vec3 sunDir;
 float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+1.),f.x),f.y);}
 void main(){vec3 d=normalize(v);float h=max(0.,d.y);vec3 night=mix(vec3(.075,.085,.15),vec3(.009,.016,.047),pow(h,.4));vec3 noon=mix(vec3(.77,.79,.76),vec3(.16,.43,.7),pow(h,.4));vec3 c=mix(night,noon,day);float sunset=1.-abs(day-.4)*2.5;c+=vec3(.45,.12,.025)*max(0.,sunset)*pow(1.-h,5.);float s=pow(max(0.,dot(d,sunDir)),750.);c+=vec3(1.,.82,.53)*s*day*2.;vec2 uv=d.xz/max(.15,d.y)*2.+time*.004;float cloud=noise(uv)*.65+noise(uv*2.)*.25+noise(uv*4.)*.1;c=mix(c,mix(vec3(.1,.13,.2),vec3(.93,.92,.88),day),smoothstep(.53,.72,cloud)*smoothstep(.02,.3,h)*.75);gl_FragColor=vec4(c,1.);}` }));sky.frustumCulled=false;scene.add(sky);
 // Equal-area hemisphere distribution avoids projection distortion and pole clustering.
 const starCount=1800,starPositions=new Float32Array(starCount*3),starBrightness=new Float32Array(starCount);
 for(let i=0;i<starCount;i++){const y=.04+.96*(i+.5)/starCount,angle=i*Math.PI*(3-Math.sqrt(5)),r=Math.sqrt(1-y*y);starPositions.set([Math.cos(angle)*r*1450,y*1450,Math.sin(angle)*r*1450],i*3);starBrightness[i]=.4+.6*((i*7919%997)/997);}
 const starGeometry=new T.BufferGeometry();starGeometry.setAttribute('position',new T.BufferAttribute(starPositions,3));starGeometry.setAttribute('brightness',new T.BufferAttribute(starBrightness,1));
 const starMaterial=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{night:{value:0},time:{value:0}},vertexShader:`attribute float brightness;varying float glow;varying vec3 direction;void main(){glow=brightness;direction=normalize(position);gl_PointSize=1.3+brightness*1.1;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float night;uniform float time;varying float glow;varying vec3 direction;
 float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+1.),f.x),f.y);}
 void main(){float disk=1.-smoothstep(.12,.5,length(gl_PointCoord-.5));vec2 uv=direction.xz/max(.15,direction.y)*2.+time*.004;float cloud=noise(uv)*.65+noise(uv*2.)*.25+noise(uv*4.)*.1;float veil=smoothstep(.53,.72,cloud)*smoothstep(.02,.3,direction.y);float alpha=disk*glow*night*(1.-veil*.92)*smoothstep(.04,.18,direction.y);if(alpha<.005)discard;gl_FragColor=vec4(.86,.91,1.,alpha);}`});
 const stars=new T.Points(starGeometry,starMaterial);stars.userData.stars=true;stars.frustumCulled=false;scene.add(stars);
 const moon=new T.Mesh(new T.SphereGeometry(14,12,10),new T.MeshBasicMaterial({color:'#d8e1ec'}));scene.add(moon);
 const poles=[],lampMaterial=new T.MeshStandardMaterial({color:'#d5d0aa',emissive:'#ffcd78',emissiveIntensity:0}),lights=[];
 const poleGeo=new T.BoxGeometry(.16,6,.16),lampGeo=new T.BoxGeometry(1.2,.16,.55),binGeo=new T.BoxGeometry(.65,1,.65);
 const lampPos=[];for(const road of world.roads){const length=Math.max(road.w,road.d);if(length<80)continue;for(let t=-length/2+24;t<length/2;t+=65){if(lampPos.length>180)break;const horizontal=road.w>road.d;const a=road.angle||0;lampPos.push(road.a?{x:road.x+Math.cos(a)*t-Math.sin(a)*(road.d/2+2),z:road.z+Math.sin(a)*t+Math.cos(a)*(road.d/2+2)}:{x:road.x+(horizontal?t:road.w/2+2),z:road.z+(horizontal?road.d/2+2:t)});}}
 const polesMesh=new T.InstancedMesh(poleGeo,new T.MeshStandardMaterial({color:'#43505a',metalness:.6,roughness:.5}),lampPos.length),lamps=new T.InstancedMesh(lampGeo,lampMaterial,lampPos.length),bins=new T.InstancedMesh(binGeo,new T.MeshStandardMaterial({color:'#344f51'}),lampPos.length);const matrix=new T.Matrix4();lampPos.forEach((p,i)=>{polesMesh.setMatrixAt(i,matrix.makeTranslation(p.x,3,p.z));lamps.setMatrixAt(i,matrix.makeTranslation(p.x,6,p.z));bins.setMatrixAt(i,matrix.makeTranslation(p.x+1,.5,p.z));});scene.add(polesMesh,lamps,bins);
 for(let i=0;i<8;i++){const light=new T.PointLight('#ffd59a',0,20,2);scene.add(light);lights.push(light);}
 // Trees and layered flower beds near the original plaza, bus shelters and street furniture.
 const props=new T.Group();scene.add(props);function box(w,h,d,x,y,z,c){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color:c,roughness:.85}));m.position.set(x,y,z);props.add(m);return m;}
 for(const [x,z] of [[-125,120],[150,-100],[-200,-180],[790,740]]){box(6,.18,2.8,x,2.8,z,'#3a525e');for(const side of [-1,1])box(.13,2.8,.13,x+side*2.8,1.4,z,'#6e858a');box(5,.5,.7,x,.6,z,'#967858');box(5,1.7,.06,x,1.7,z-1,'#6b959e');}

 const water=new T.Mesh(new T.PlaneGeometry(500,3000),new T.ShaderMaterial({transparent:true,uniforms:{time:{value:0},day:{value:1}},vertexShader:'varying vec2 uvp;void main(){uvp=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 uvp;uniform float time;uniform float day;void main(){float w=sin(uvp.x*140.+time)*sin(uvp.y*250.+time*.6);vec3 col=mix(vec3(.018,.04,.07),vec3(.1,.38,.47),day)+w*.025;gl_FragColor=vec4(col,.94);}'}));water.rotation.x=-Math.PI/2;water.position.set(1490,.04,0);scene.add(water);box(35,.05,3000,1225,.025,0,'#b9ad89');
 const windowMats=new Set();scene.traverse(m=>{if(m.material?.color&&['3c6076','446575','526d80','344e64','455d70'].includes(m.material.color.getHexString()))windowMats.add(m.material);});for(const mat of windowMats)mat.emissive?.set('#e5ba77');
 const hemi=scene.children.find(m=>m.isHemisphereLight);
 return{get hour(){return clock;},set hour(v){clock=v%24;},get cycle(){return cycle;},set cycle(v){cycle=v;},tick(dt,pos,indoors=false){if(cycle)clock=(clock+dt/55)%24;const a=(clock-6)/24*Math.PI*2,day=T.MathUtils.smoothstep(Math.sin(a),-.18,.3);const dir=new T.Vector3(Math.cos(a)*.6,Math.sin(a),.35).normalize();sky.position.copy(pos);stars.position.copy(pos);starMaterial.uniforms.night.value=Math.pow(1-day,4);starMaterial.uniforms.time.value+=dt;stars.visible=day<.95;sky.material.uniforms.day.value=day;sky.material.uniforms.time.value+=dt;water.material.uniforms.time.value+=dt;water.material.uniforms.day.value=day;for(const mat of windowMats)mat.emissiveIntensity=(1-day)*.7;sky.material.uniforms.sunDir.value.copy(dir);sun.position.copy(pos).addScaledVector(dir,70);sun.target.position.copy(pos);sun.target.updateMatrixWorld();sun.intensity=.1+day*2.7;if(hemi)hemi.intensity=.4+day*1.6;scene.fog.color.setRGB(.07+day*.56,.09+day*.59,.15+day*.55);moon.position.copy(pos).addScaledVector(dir,-1400);moon.visible=day<.5;lampMaterial.emissiveIntensity=(1-day)*2.2;const nearest=lampPos.filter(p=>Math.hypot(p.x-pos.x,p.z-pos.z)<80).sort((a,b)=>Math.hypot(a.x-pos.x,a.z-pos.z)-Math.hypot(b.x-pos.x,b.z-pos.z));lights.forEach((l,i)=>{const p=nearest[i];l.intensity=p&&!indoors?(1-day)*28:0;if(p)l.position.set(p.x,5.7,p.z);});return{night:1-day,hour:clock};}};
}
