export const SOUND_FILES={shot_pistol:'pistol.mp3',shot_rifle:'rifle.mp3',shot_shotgun:'shotgun.mp3',shot_sniper:'sniper.mp3',shot_smg:'smg.mp3',explosion:'explosion.mp3',fire:'fire.mp3',fire_crackle:'fire_crackle.mp3',bomb_plant:'bomb_plant.mp3',detonator:'detonator.mp3',bottle_pickup:'bottle_pickup.mp3',toast:'toast.mp3',toast_call:'toast_call.mp3',party_cheer:'party_cheer.mp3',drink:'drink.mp3',mission_start:'mission_start.mp3',mission_complete:'mission_complete.mp3',door_breach:'door_breach.mp3',glass_break:'glass_break.mp3',stun:'stun.mp3',baton:'baton.mp3',terminal:'terminal.mp3',ram_pickup:'ram_pickup.mp3',spikes:'spikes.mp3',forklift:'forklift.mp3',convoy_stop:'convoy_stop.mp3',radio_switch:'radio_switch.mp3',cash_pickup:'cash_pickup.mp3',shop_buy:'shop_buy.mp3',weapon_draw:'weapon_draw.mp3',dry_fire:'dry_fire.mp3',final_choice:'final_choice.mp3',shot:'bullet.mp3',reload:'reload.mp3',hit:'hit.mp3',hurt:'hurt.mp3',crash:'crash.mp3',step:'footstep.mp3',fail:'mission_fail.mp3',objective:'objective.mp3',bird:'birds.mp3',siren:'siren.mp3',drift:'tire_screech.mp3',engine:'engine.mp3',scooter:'kukirin.mp3',wind:'wind.mp3'};
export const MUSIC_FILES={mission5:'mission5.mp3',mission6:'mission6.mp3',mission7:'mission7.mp3',mission8:'lastsong.mp3',prologue:'prologue.mp3',memory:'mission2.mp3',denial:'mission3.mp3',free:'free_roam.mp3'};
export const SCORES={prologue:{name:'Basement Heat',bpm:96,root:38,melody:[12,15,19,22,19,15,14,10],chords:[0,5,3,7]},memory:{name:'Volatile Memory',bpm:118,root:33,melody:[19,15,12,10,14,17,22,19],chords:[0,3,7,5]},denial:{name:'Access Denied',bpm:132,root:30,melody:[12,24,19,15,22,19,14,17],chords:[0,7,5,3]},free:{name:'Coastal Afterhours',bpm:86,root:36,melody:[16,19,24,23,19,16,14,12],chords:[0,5,9,7]}};
for(const [id,name,bpm]of [[5,'Kopernik Falls',126],[6,'Bottleneck',136],[7,'Ekonom Reclaimed',140],[8,'End of Shift',80]])SCORES['mission'+id]={...SCORES.memory,name,bpm,root:id===8?36:30};
export class GameAudio{
 constructor(){this.musicVolume=.35;this.sfxVolume=.6;this.masterVolume=.8;this.nextBeat=0;this.step=0;this.track='free';this.foot=0;this.bird=0;this.reloadSeen=false;this.customBuffers=new Map();this.customLoops=new Map();this.fileMusic={};this.musicAllowed=false;this.musicFadeIn=1.4;this.musicFadeOut=1.2;this.synthTrack='free';this.synthLevel=0;}
 async start(){if(!this.ctx){const AudioContext=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioContext)return;const c=this.ctx=new AudioContext();this.master=c.createGain();this.master.connect(c.destination);this.music=c.createGain();this.music.connect(this.master);this.sfx=c.createGain();this.sfx.connect(this.master);
  const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.5;this.noiseBuffer=buffer;
  this.motor=c.createOscillator();this.motor.type='sawtooth';this.motorGain=c.createGain();this.motorGain.gain.value=0;this.motor.connect(this.motorGain).connect(this.sfx);this.motor.start();
  const wind=c.createBufferSource();wind.buffer=buffer;wind.loop=true;const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=420;this.wind=c.createGain();this.wind.gain.value=.035;wind.connect(filter).connect(this.wind).connect(this.sfx);wind.start();
 }this.loadCustomSounds();for(const file of Object.values(this.fileMusic))file.blocked=false;await this.ctx.resume().catch(()=>{});}
 loadCustomSounds(){
  if(this.customLoaded)return;this.customLoaded=true;
  if(globalThis.location?.protocol==='file:')this.localSoundFiles=new Set(globalThis.GTA6_SOUND_FILES||[]);
  else if(typeof this.ctx?.decodeAudioData==='function'&&typeof fetch==='function')for(const [name,file] of Object.entries(SOUND_FILES))fetch(new URL('./sounds/'+file,import.meta.url),{cache:'no-store'}).then(r=>r.ok?r.arrayBuffer():Promise.reject()).then(data=>this.ctx.decodeAudioData(data)).then(buffer=>this.customBuffers.set(name,buffer)).catch(()=>{});
  if(typeof Audio==='function')for(const [track,file] of Object.entries(MUSIC_FILES)){
   const element=new Audio();const entry=this.fileMusic[track]={element,ready:false,blocked:false,pending:false,level:0,restart:false};element.loop=true;element.preload='auto';element.volume=0;
   element.addEventListener('canplay',()=>entry.ready=true);element.addEventListener('error',()=>{entry.ready=false;entry.blocked=true;element.pause();});element.src=new URL('./sounds/'+file,import.meta.url).href;element.load?.();
  }
 }
 customEffect(name,power=1,pitch=1){const buffer=this.customBuffers.get(name);if(!buffer){const file=SOUND_FILES[name];if(!file||!this.localSoundFiles?.has(file))return false;const element=new Audio(new URL('./sounds/'+file,document.baseURI).href);element.volume=Math.min(1,Math.max(0,power*this.masterVolume*this.sfxVolume));element.playbackRate=pitch;element.play().catch(()=>{});return true;}const source=this.ctx.createBufferSource(),gain=this.ctx.createGain();source.buffer=buffer;if(source.playbackRate)source.playbackRate.value=pitch;gain.gain.value=Math.min(1,Math.max(0,power));source.connect(gain).connect(this.sfx);source.start();source.onended=()=>{source.disconnect();gain.disconnect();};return true;}
 customLoop(name,volume,rate=1){const buffer=this.customBuffers.get(name);if(!buffer){const file=SOUND_FILES[name];if(!file||!this.localSoundFiles?.has(file))return false;let element=this.customLoops.get(name);if(!element){element=new Audio(new URL('./sounds/'+file,document.baseURI).href);element.loop=true;this.customLoops.set(name,element);element.play().catch(()=>{});}element.volume=Math.min(1,Math.max(0,volume*this.masterVolume*this.sfxVolume));element.playbackRate=rate;return true;}let loop=this.customLoops.get(name);if(!loop){const source=this.ctx.createBufferSource(),gain=this.ctx.createGain();source.buffer=buffer;source.loop=true;gain.gain.value=0;source.connect(gain).connect(this.sfx);source.start();loop={source,gain};this.customLoops.set(name,loop);}loop.gain.gain.setTargetAtTime(volume,this.ctx.currentTime,.15);loop.source.playbackRate?.setTargetAtTime(rate,this.ctx.currentTime,.1);return true;}
 updateFileMusic(active,radio,dt){
  this.musicAllowed=active&&!radio;const current=this.fileMusic[this.track];
  const volume=Math.max(0,Math.min(1,this.masterVolume*this.musicVolume));
  for(const [track,entry] of Object.entries(this.fileMusic)){
   if(entry.restart&&entry.level<=0){entry.element.currentTime=0;entry.restart=false;}
   const allowed=this.musicAllowed&&track===this.track&&entry.ready&&!entry.blocked&&!entry.restart;
   entry.level=Math.max(0,Math.min(1,entry.level+(allowed?dt/this.musicFadeIn:-dt/this.musicFadeOut)));
   entry.element.volume=volume*entry.level;
   // Let the outgoing song finish its fade before pausing it at its current position.
   if(entry.level<=0&&!allowed){entry.element.pause();continue;}
   if(allowed&&entry.element.paused&&!entry.pending){entry.pending=true;Promise.resolve(entry.element.play()).then(()=>{if(entry.level<=0)entry.element.pause();}).catch(()=>{entry.blocked=true;entry.level=0;entry.element.volume=0;}).finally(()=>entry.pending=false);}
  }
  return !!current?.ready&&!current.blocked;
 }

 tone(freq,time,length,gain=.15,type='triangle',bus=this.sfx,end=freq){if(!this.ctx)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(Math.max(15,freq),time);o.frequency.exponentialRampToValueAtTime(Math.max(15,end),time+length);g.gain.setValueAtTime(.001,time);g.gain.linearRampToValueAtTime(gain,time+.008);g.gain.exponentialRampToValueAtTime(.001,time+length);o.connect(g).connect(bus);o.start(time);o.stop(time+length+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
 noise(time,length,gain,cutoff=2500,pitch=1){if(!this.ctx)return;const c=this.ctx,s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=this.noiseBuffer;if(s.playbackRate)s.playbackRate.value=pitch;f.type='lowpass';f.frequency.value=cutoff*pitch;g.gain.setValueAtTime(gain,time);g.gain.exponentialRampToValueAtTime(.001,time+length);s.connect(f).connect(g).connect(this.sfx);s.start(time);s.stop(time+length);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect();};}
 effect(name,power=1){if(!this.ctx)return;const variation=name.startsWith('shot')?.03:name==='step'?.05:0,pitch=variation?1+(Math.random()*2-1)*variation:1;if(this.customEffect(name,power,pitch))return;if(name.startsWith('shot_')){name='shot';if(this.customEffect(name,power,pitch))return;}const t=this.ctx.currentTime;if(name==='shot'){this.noise(t,.12,.55*power,5000,pitch);this.tone(130*pitch,t,.16,.4*power,'triangle',this.sfx,35*pitch);}if(name==='reload'){this.noise(t,.08,.2,1800);this.noise(t+.45,.09,.17,2500);this.tone(380,t+.65,.05,.08,'square');}if(name==='hit')this.tone(700,t,.045,.08,'sine',this.sfx,160);if(name==='hurt'){this.noise(t,.15,.3,650);this.tone(95,t,.2,.2,'sine',this.sfx,40);}if(name==='explosion'){this.noise(t,1.4,.85,900);this.tone(75,t,1.7,.5,'sine',this.sfx,18);}if(name==='fire_crackle')this.noise(t,.25,.1,1600);if(['bottle_pickup','toast','detonator','bomb_plant','terminal','ram_pickup','cash_pickup','shop_buy','weapon_draw','spikes'].includes(name)){this.noise(t,.06,.1,2100);this.tone(500,t,.08,.055,'sine');}if(name==='glass_break')this.noise(t,.5,.35,6500);if(name==='door_breach'||name==='baton'||name==='convoy_stop')this.noise(t,.18,.35,1000);if(name==='stun')this.tone(110,t,.25,.12,'sawtooth');if(name==='crash')this.noise(t,.3,Math.min(.7,power*.4),1500);if(name==='step')this.noise(t,.055,.1,800,pitch);if(name==='fail'){this.tone(196,t,1,.15,'sawtooth',this.sfx,49);}if(name==='objective'){for(let i=0;i<3;i++)this.tone([440,554,660][i],t+i*.09,.22,.1,'sine');}}
 beat(time){const score=SCORES[this.synthTrack],n=this.step++,bar=Math.floor(n/16),chord=score.chords[bar%4],hz=m=>440*2**((m-69)/12),interval=60/score.bpm/4;
  if(n%4===0)this.tone(130,time,.17,.23,'sine',this.music,40);if(n%8===4){this.tone(175,time,.07,.14,'triangle',this.music,80);this.tone(2800,time,.025,.055,'square',this.music,1700);}if(n%2===0)this.tone(6000,time,.022,.026,'square',this.music,3500);
  if(n%2===0)this.tone(hz(score.root+chord),time,interval*1.7,.15,'sawtooth',this.music);
  if(n%2===0)this.tone(hz(score.root+score.melody[Math.floor(n/2)%8]+chord),time,interval*2.4,.065,'triangle',this.music);
  if(n%16===0)for(const shift of [12,15,19])this.tone(hz(score.root+chord+shift),time,interval*14,.025,'sine',this.music);
 }
 tick(dt,{active,mission,car,speed=0,grounded=true,night=0,indoors=false,radio=false,alert=false}){if(!this.ctx)return;const c=this.ctx,t=c.currentTime,carSpeed=Number.isFinite(car?.speed)?car.speed:0;this.master.gain.setTargetAtTime(active?this.masterVolume:0,t,.2);if(mission!==this.track&&SCORES[mission]){this.track=mission;const entry=this.fileMusic[mission];if(entry)entry.restart=true;}
  dt=Math.max(0,Math.min(.2,Number.isFinite(dt)?dt:0));
  const customMusic=this.updateFileMusic(active,radio,dt);
  // The built-in score also fades out before changing composition, then fades in.
  if(this.synthTrack!==this.track&&this.synthLevel<=0){this.synthTrack=this.track;this.step=0;this.nextBeat=t+.1;}
  const synthAllowed=active&&!radio&&!customMusic&&this.synthTrack===this.track;
  this.synthLevel=Math.max(0,Math.min(1,this.synthLevel+(synthAllowed?dt/this.musicFadeIn:-dt/this.musicFadeOut)));
  this.music.gain.setTargetAtTime(this.synthLevel*this.musicVolume,t,.025);this.sfx.gain.setTargetAtTime(this.sfxVolume,t,.15);if(!active){this.nextBeat=t;return;}
  if(radio||customMusic)this.nextBeat=t;else while(this.nextBeat<t+.12){if(this.nextBeat<t-.2)this.nextBeat=t;this.beat(this.nextBeat);this.nextBeat+=60/SCORES[this.synthTrack].bpm/4;}
  this.motor.type=car?.kind==='scooter'?'sine':'sawtooth';this.motor.frequency.setTargetAtTime(car?45+Math.abs(carSpeed)*6:40,t,.08);const forkliftFile=this.customLoop('forklift',car?.kind==='forklift'?.3:0,car?1+Math.abs(carSpeed)*.025:1);const engineFile=forkliftFile&&car?.kind==='forklift'?true:this.customLoop('engine',car&&car.kind!=='scooter'?.3:0,car?1+Math.abs(carSpeed)*.025:1),scooterFile=this.customLoop('scooter',car?.kind==='scooter'?.3:0,car?1+Math.abs(carSpeed)*.025:1);this.motorGain.gain.setTargetAtTime(car&&!(car.kind==='scooter'?scooterFile:engineFile)?(car.kind==='scooter'?.025:.055):0,t,.15);
  const customWind=this.customLoop('wind',indoors?.04:.12+Math.abs(carSpeed)*.002);this.wind.gain.setTargetAtTime(customWind?0:indoors?.008:.025+Math.abs(carSpeed)*.001,t,.8);
  this.foot-=dt;if(!car&&speed>.6&&grounded&&this.foot<=0){this.effect('step');this.foot=speed>5?.27:.43;}
  this.bird-=dt;if(this.bird<=0){if(alert){if(!this.customEffect('siren',.2)){this.tone(650,t,.6,.035,'sine',this.sfx,950);this.tone(950,t+.6,.6,.035,'sine',this.sfx,650);}}else if(!indoors){if(!this.customEffect('bird',.25)){this.tone(night>.5?2800:1800,t,.1,.015,'sine',this.sfx,night>.5?2900:2600);this.tone(night>.5?2800:2100,t+.17,.12,.012,'sine',this.sfx,2600);}}this.bird=alert?1.2:2+Math.random()*5;}
  this.customLoop('drift',car?.drifting?.52:0);if(car?.drifting&&!this.customBuffers.has('drift')&&Math.random()<dt*10)this.noise(t,.1,.13,3300);
 }
}
