import {MAP} from './map-layout.js?v=roof-seat-2';
// Fictional offline puzzle: no networking, real targets, or attack tooling.
export function createDenialMission(T,api,barn){
 const $=id=>document.getElementById(id),school=MAP.locations.piastowska,route=MAP.ride,back=MAP.back;
 let stage='locked',time=0,held=false,hold=0,index=0,nodes=[0,0,0],configured=false,load=0,heat=0,loot=0,broken=0,sequenceIndex=0,stationIndex=-1,alert=0,activePC=null,feedbackUntil=0,assets=[],roads=[],pcs=[],patrols=[],scooters=[],team=[],puffs=[],advanced=[],gate,barrier,exitWindow,serverLight,crew;
 const seq=['KeyQ','KeyZ','KeyX'];
 const say=(title,goal,line)=>{$('missiontitle').textContent=title;$('missionobjective').textContent=goal;$('missiondialog').textContent=line;$('missionprompt').textContent='';};
 const move=(x,z)=>api.teleport(x,z),control=(ch,label,index=-1)=>{api.switchControl?.(ch,label,index);api.holster();};
 function build(){const before=new Set(api.scene.children),box=api.box;
  box(52,.08,40,school.x,.03,school.z,'#b5aca0');for(const side of [-1,1])box(.4,6,40,school.x+side*26,3,school.z,'#c5b397',true);box(52,6,.4,school.x,3,school.z-20,'#c5b397',true);
  for(const side of [-1,1])box(22,6,.4,school.x+side*15,3,school.z+20,'#c5b397',true);gate=box(8,3,.4,school.x,1.5,school.z+20,'#344e61',true);box(8,3,.4,school.x,4.5,school.z+20,'#c5b397',true);box(53,.4,41,school.x,6.2,school.z,'#c5b397',true);
  const label=api.sign('PIASTOWSKA / SZKOŁA',18,1.5);label.position.set(school.x,5.2,school.z+20.45);api.scene.add(label);
  for(const side of [-1,1])for(let i=0;i<4;i++)box(2.5,1.5,.05,school.x+side*(9+i*4),3.3,school.z+20.3,'#486d83');
  for(let row=0;row<3;row++)for(let col=0;col<4;col++){const x=school.x-18+col*12,z=school.z-13+row*10;box(4,.15,2,x,1,z,'#846d55',true);const pc=box(.7,.9,.8,x+.8,1.55,z,'#3c454c');box(1.4,1,.12,x-.8,1.65,z,'#2d3d4a');box(1,.05,.35,x-.8,1.15,z+1,'#828c93');const panel=new T.Mesh(new T.BoxGeometry(.035,.8,.7),pc.material);panel.position.set(.37,0,0);pc.add(panel);pcs.push({x,z:z+2,mesh:pc,panel,remaining:3,open:false});}
  exitWindow=box(.4,3,4,school.x+26,1.5,school.z+9,'#6a91a2',true);barrier=box(5,1.8,.5,school.x+8,.9,school.z+17,'#3f4851');barrier.visible=false;for(let i=0;i<4;i++){const crt=new T.Mesh(new T.BoxGeometry(1,.8,.8),new T.MeshStandardMaterial({color:'#b2aa96'}));crt.position.set(-1.8+i*1.2,.25,(i%2)*.2);barrier.add(crt);const screen=new T.Mesh(new T.BoxGeometry(.8,.55,.04),new T.MeshStandardMaterial({color:'#33474d'}));screen.position.set(0,0,.43);crt.add(screen);}
  // Side-window opening in the east wall, usable for the evacuation.
  const sideWall=api.scene.children.find(m=>!before.has(m)&&m.position.x===school.x+26&&m.geometry?.parameters.depth===40);api.toggleContent?.([sideWall],[],false);
  box(.4,6,27,school.x+26,3,school.z-6.5,'#c5b397',true);box(.4,6,9,school.x+26,3,school.z+15.5,'#c5b397',true);box(.4,3,4,school.x+26,4.5,school.z+9,'#c5b397',true);
  // Routes and school approaches are permanent world roads, without duplicate layers.
  for(let i=0;i<4;i++){const guard=api.character({shirt:'#30435c',pants:'#242e3b',skin:'#c99e7b',hair:'#222831'});guard.root.position.set(700+i*75,0,-850);patrols.push({ch:guard,x:700+i*75,z:-850,phase:i});}
  for(let i=0;i<3;i++){const scooter=api.makeScooter(barn.x-8+i*3,barn.z-25);scooters.push(scooter);if(i){const ch=api.character({shirt:'#414b5c',pants:'#272f37',skin:'#c99e7b',hair:'#252a2e'});ch.root.visible=false;team.push(ch);}}
  crew=api.character({shirt:'#616b7d',pants:'#242c34',skin:'#c99e7b',hair:'#252a2e'});crew.root.visible=false;for(const ch of team){const gun=new T.Mesh(new T.BoxGeometry(.13,.16,.65),new T.MeshStandardMaterial({color:'#252d36'}));gun.position.set(.5,1.3,.35);ch.body.add(gun);}
  for(let i=0;i<9;i++){const puff=new T.Mesh(new T.IcosahedronGeometry(.35,0),new T.MeshBasicMaterial({color:'#89999e',transparent:true,opacity:.3}));puff.position.set(barn.x-9+(i%3)*.4,1+(i%4)*.5,barn.z-4);api.scene.add(puff);puffs.push(puff);}
  serverLight=new T.PointLight('#72fc92',0,16,2);serverLight.position.set(barn.x-9,2,barn.z-4);api.scene.add(serverLight);
  assets=api.scene.children.filter(m=>!before.has(m)&&m!==sideWall);api.toggleContent?.(assets,roads,true);
 }
 function start(){if(stage!=='ready')return;if(!scooters.length)build();else{api.toggleContent?.(assets,roads,true);api.toggleContent?.([gate],[],true);gate.visible=true;exitWindow.visible=true;api.toggleContent?.([exitWindow],[],true);barrier.visible=false;pcs.forEach(pc=>{pc.remaining=3;pc.open=false;pc.panel.rotation.z=0;});for(let i=0;i<scooters.length;i++){const s=scooters[i];s.x=barn.x-8+i*3;s.z=barn.z-25;s.speed=0;s.yaw=0;s.root.position.set(s.x,0,s.z);}puffs.forEach(m=>m.visible=true);serverLight.intensity=0;}stage='logic';time=0;nodes=[0,0,0];load=0;heat=0;configured=false;loot=0;broken=0;index=0;control(api.chars[2],'MACIOSZEK',2);$('networkgame').hidden=false;say('MISJA 3 / ODMOWA DOSTĘPU','Połącz trzy symboliczne węzły. 6 / 7 / 8 zmieniają wyjście każdego węzła.','Macioszek: Wybierz drogę: B → C → A. Bystrek: Pilnuję chłodzenia.');}
 function launch(){configured=true;stage='cooling';time=0;control(api.chars[0],'BYSTREK',0);say('01 / PRZECIĄŻENIE ŁĄCZY','Utrzymaj temperaturę poniżej 100%. F chłodzi instalację w odpowiednim momencie.','Macioszek: Symulacja obciążenia ruszyła. Bystrek, schładzaj, gdy temperatura rośnie!');}
 function infiltrate(){stage='ride';time=0;index=0;hold=0;$('networkgame').hidden=true;control(api.chars[1],'BEJNAR',1);say('02 / CICHY PODJAZD','E · dowolny pojazd. Jedź za znacznikiem i omijaj patrole.','Macioszek: Alarmy i zamki Piastowskiej są wyłączone. Bejnar: Ruszamy bocznymi ulicami.');}
 function breach(){api.sound?.('door_breach');stage='breach';time=0;control(api.chars[1],'BEJNAR',1);say('03 / WEJŚCIE DO SZKOŁY','Przytrzymaj F przy głównych drzwiach, aby wyłamać zamek.','Pierwsza pe: Mamy łomy. Pracownia jest za tymi drzwiami.');}
 function beginLoot(){gate.visible=false;api.toggleContent?.([gate],[],false);stage='loot';time=0;activePC=null;control(crew,'DRUGA PE');team.forEach((ch,i)=>{ch.root.visible=true;ch.root.position.set(school.x+(i?6:-6),0,school.z+16);ch.root.rotation.y=Math.PI;});$('ramsequence').hidden=false;say('04 / ŻNIWA NA PŁYTACH','75 sekund. F otwiera obudowę; Q / Z / X wyjmują RAM w pokazanej kolejności.','Bejnar: Pilnujemy drzwi. Pomyłka łamie moduł — działaj precyzyjnie.');}
 function retreat(){stage='escape';time=0;index=0;barrier.visible=true;exitWindow.visible=false;api.toggleContent?.([exitWindow],[],false);control(api.chars[1],'BEJNAR',1);$('ramsequence').hidden=true;say('05 / EWAKUACJA NA DWÓCH KOŁACH','Wyjdź przez okno na parterze. E · dowolny pojazd. Wróć trasą do stodoły.','Pierwsza pe: CRT-y blokują korytarz! Bejnar: Torby na plecy, gaz!');}
 function install(){stage='install';time=0;hold=0;control(api.chars[0],'BYSTREK',0);for(const ch of team)ch.root.visible=false;patrols.forEach(p=>p.ch.root.visible=false);say('06 / NOWA MOC','F przy serwerowni: zainstaluj RAM zdobyty w Piastowskiej.','Macioszek: Sloty czekają. Następny cel: Kopernika.');}
 function complete(){stage='complete';api.missionComplete?.(3);serverLight.intensity=45;puffs.forEach(m=>m.visible=false);$('advancedpanel').hidden=false;document.querySelector?.('#paused section')?.append?.($('advancedpanel'));say('ODMOWA DOSTĘPU / UKOŃCZONA',loot*32+' GB z Piastowskiej · Esc: zaawansowane technologie','Bejnar: Moc serwerowni wzrosła. Opcje przygotowania kolejnego uderzenia odblokowane.');api.upgrade?.('advanced');}
 function interact(dt,p,x,z,label,seconds,done){if(Math.hypot(p.x-x,p.z-z)<2.8&&!api.state().driving){$('missionprompt').textContent=label+' · '+Math.floor(hold/seconds*100)+'%';hold=held?hold+dt:0;if(hold>=seconds){hold=0;held=false;done();}}else hold=0;return{x,z};}
 function input(code){if(!api.active())return;if(stage==='logic'&&['Digit6','Digit7','Digit8'].includes(code)){nodes[+code.slice(-1)-6]=(nodes[+code.slice(-1)-6]+1)%3;if(nodes.join(',')==='1,2,0')launch();}
  if(stage==='loot'&&activePC&&seq.includes(code)){if(code===seq[(stationIndex+sequenceIndex)%3]){sequenceIndex++;if(sequenceIndex===3){loot++;activePC.remaining--;sequenceIndex=0;$('ramfeedback').textContent='Moduł zabezpieczony! +32 GB';feedbackUntil=time+1.2;}}else{broken++;activePC.remaining--;sequenceIndex=0;$('ramfeedback').textContent='Błędny klawisz — moduł uszkodzony. Zacznij kolejną sekwencję.';feedbackUntil=time+1.8;}if(activePC.remaining<=0)activePC=null;}
 }
 function tick(dt){if(stage==='locked'||!api.active())return null;time+=dt;const p=api.state().position,driving=api.state().driving;$('missionprompt').textContent='';let target=null;
  if(stage==='ready'){const b=api.chars[1].root.position;target=interact(dt,p,b.x,b.z,'F · Bejnar: Odmowa Dostępu',1,start);}
  else if(stage==='logic'){$('networktitle').textContent='USTAW POŁĄCZENIA';$('networkrouting').hidden=false;$('networkcooling').hidden=true;for(let i=0;i<3;i++){const b=$('node'+(i+6)),goal=[1,2,0][i];b.textContent=(i+6)+' · '+['A','B','C'][nodes[i]]+' → cel '+['A','B','C'][goal];b.className=nodes[i]===goal?'correct':'';}$('networknodes').textContent='Węzły 6 / 7 / 8: '+nodes.map(n=>['A','B','C'][n]).join(' → ')+' | cel: B → C → A';target={x:barn.x-9,z:barn.z-5};}
  else if(stage==='cooling'){load+=dt*3.4;heat+=dt*12;const near=Math.hypot(p.x-(barn.x-9),p.z-(barn.z-5))<3;
   if(held&&near&&heat>=45){heat=Math.max(0,heat-dt*38);$('missionprompt').textContent='CHŁODZENIE · wódka na chłodnicę';}else $('missionprompt').textContent=heat>=45?'F · teraz schłodź instalację':'Poczekaj: chłodzenie potrzebne powyżej 45%';
   $('networkload').value=load;$('networkheat').value=heat;$('networknodes').textContent='Obciążenie '+Math.floor(load)+'% · temperatura '+Math.floor(heat)+'%';puffs.forEach((m,i)=>{m.scale.setScalar(.8+heat/70);m.position.y=1+(i%4)*.5+Math.sin(time+i)*.1;});target={x:barn.x-9,z:barn.z-5};if(heat>=100){if(api.fail){api.fail('Serwerownia spłonęła przez przegrzanie.');return;}load=0;heat=0;time=0;$('missiondialog').textContent='Przegrzanie. Punkt kontrolny: ponów chłodzenie.';}else if(load>=100)infiltrate();
  }else if(stage==='ride'||stage==='escape'){
   const path=stage==='ride'?route:back;target={x:path.at(-1)[0],z:path.at(-1)[1]};if(!driving){const sc=api.nearestVehicle?.()||scooters.reduce((best,s)=>Math.hypot(p.x-s.x,p.z-s.z)<Math.hypot(p.x-best.x,p.z-best.z)?s:best,scooters[0]);target={x:sc.x,z:sc.z};}
   patrols.forEach((guard,i)=>{if(!guard.ch.root.parent)return;guard.ch.root.visible=true;guard.ch.root.position.set(guard.x+Math.sin(time*.4+i)*12,0,guard.z);guard.ch.root.rotation.y=-Math.PI/2;api.animate?.(guard.ch,dt,1,false,false);});
   if(driving){for(let i=0;i<team.length;i++){const ch=team[i],sc=scooters.filter(s=>s!==driving)[i];ch.root.visible=true;if(api.driveAI){api.driveAI(sc,{x:driving.x,z:driving.z,speed:Math.min(24,Math.abs(driving.speed)+4),gap:5+i*4},dt);}else{sc.x=driving.x-Math.sin(driving.yaw)*(4+i*3)+(i-.5)*1.4;sc.z=driving.z-Math.cos(driving.yaw)*(4+i*3);sc.yaw=driving.yaw;}if(!api.driveAI){sc.root.position.set(sc.x,0,sc.z);sc.root.rotation.y=sc.yaw;}ch.root.position.set(sc.x,.3,sc.z);ch.root.rotation.y=sc.yaw;api.poseRider?.(ch,sc);}
    const seen=patrols.some(g=>Math.hypot(p.x-g.ch.root.position.x,p.z-g.ch.root.position.z)<17);alert=Math.max(0,Math.min(100,alert+dt*(seen?30:-14)));if(alert>=100){if(api.fail){api.fail('Patrol wykrył ekipę.');return;}const previous=path[Math.max(0,index-1)];driving.x=previous[0];driving.z=previous[1];driving.speed=0;driving.root.position.set(driving.x,0,driving.z);alert=0;$('missiondialog').textContent='Patrol zauważył ekipę. Wróć na boczną trasę — punkt kontrolny.';}
    if(Math.hypot(driving.x-target.x,driving.z-target.z)<11){stage=stage==='ride'?'parkSchool':'parkHome';say('ZATRZYMAJ SIĘ','Zatrzymaj pojazd i wysiądź: E.','Bejnar: Jesteśmy na miejscu.');}
   }else $('missionprompt').textContent='E · wsiądź do dowolnego pojazdu';
   if(stage==='ride'||stage==='escape')$('missionobjective').textContent=(stage==='ride'?'Jedź do Piastowskiej':'Wróć do stodoły')+' · wykrycie '+Math.floor(alert)+'%';
  }else if(stage==='parkSchool'||stage==='parkHome'){const point=(stage==='parkSchool'?route:back).at(-1);target={x:point[0],z:point[1]};if(!driving&&Math.hypot(p.x-point[0],p.z-point[1])<18){if(stage==='parkSchool')breach();else install();}
  }else if(stage==='breach')target=interact(dt,p,school.x,school.z+23,'F · łom: wyłam drzwi',1.5,beginLoot);
  else if(stage==='loot'){const pc=pcs.find(pc=>pc.remaining>0&&Math.hypot(p.x-pc.x,p.z-pc.z)<3)||pcs.find(pc=>pc.remaining>0);if(pc){target={x:pc.x,z:pc.z};if(Math.hypot(p.x-pc.x,p.z-pc.z)<3){if(!pc.open)target=interact(dt,p,pc.x,pc.z,'F · zerwij boczną obudowę',.5,()=>{pc.open=true;pc.panel.rotation.z=.7;activePC=pc;stationIndex=pcs.indexOf(pc);sequenceIndex=0;});else if(activePC!==pc){activePC=pc;stationIndex=pcs.indexOf(pc);sequenceIndex=0;}}else activePC=null;}
   for(let i=0;i<3;i++){const step=$('ramstep'+i);step.textContent=activePC?seq[(stationIndex+i)%3].slice(3):'—';step.className=activePC?(i<sequenceIndex?'done':i===sequenceIndex?'next':''):'';}for(const code of seq){const button=$('ram'+code.slice(3).toLowerCase());button.disabled=!activePC;button.className=activePC&&code===seq[(stationIndex+sequenceIndex)%3]?'next':'';}if(time>feedbackUntil)$('ramfeedback').textContent='';
   $('ramkeys').textContent=activePC?'Naciśnij teraz: '+seq[(stationIndex+sequenceIndex)%3].slice(3)+' · '+sequenceIndex+' / 3 poprawnych':'Podejdź do stanowiska i otwórz obudowę';$('ramtimer').value=time;$('missionobjective').textContent='Pozostało '+Math.max(0,Math.ceil(75-time))+' s · RAM '+loot*32+' GB · uszkodzone '+broken;
   if(loot>=9||time>=75||pcs.every(pc=>pc.remaining===0)){if(loot===0){if(api.fail){api.fail('Nie zdobyto żadnego sprawnego modułu RAM.');return;}time=0;pcs.forEach(pc=>pc.remaining=3);$('missiondialog').textContent='Brak sprawnych modułów. Powtórka od pracowni.';}else retreat();}
  }else if(stage==='install')target=interact(dt,p,barn.x-9,barn.z-5,'F · wpinaj RAM do serwerowni',3,complete);
  return target;
 }
 function unlock(){stage='ready';say('MISJA 3 / BEJNAR','F · porozmawiaj z Bejnarem o Piastowskiej.','Bejnar: Serwery komendy to był początek. Teraz pracownie Piastowskiej.');}
 function reset(){api.toggleContent?.(assets,roads,false);stage='locked';held=false;hold=0;configured=false;advanced=[];for(const [id,label] of [['advancedquiet','Przygotuj profil: tryb cichy'],['advancedwindow','Przygotuj profil: dłuższe okno infiltracji'],['advancedplan','Odblokuj plan Kopernika']]){$(id).disabled=false;$(id).textContent=label;}for(const id of ['networkgame','ramsequence','advancedpanel'])$(id).hidden=true;}
 addEventListener('keydown',e=>{if(e.code==='KeyF')held=true;if(!e.repeat)input(e.code);});addEventListener('keyup',e=>{if(e.code==='KeyF')held=false;});addEventListener('blur',()=>held=false);$('interact').addEventListener('pointerdown',()=>held=true);for(const e of ['pointerup','pointercancel','pointerleave'])$('interact').addEventListener(e,()=>held=false);
 for(const [id,key] of [['node6','Digit6'],['node7','Digit7'],['node8','Digit8'],['ramq','KeyQ'],['ramz','KeyZ'],['ramx','KeyX']])$(id).onclick=()=>input(key);
 for(const [id,key] of [['advancedquiet','quiet'],['advancedwindow','window'],['advancedplan','kopernika']])$(id).onclick=()=>{if(stage!=='complete'||advanced.includes(key))return;advanced.push(key);$(id).disabled=true;$(id).textContent+=' ✓';$('missiondialog').textContent=key==='kopernika'?'Plan Kopernika odblokowany; kolejny napad czeka na nowy rozdział.':'Profil zaawansowany zapisany w serwerowni: '+(key==='quiet'?'tryb cichy':'wydłużone okno infiltracji');};
 function restoreComplete(){if(!scooters.length)build();stage='complete';loot=9;serverLight.intensity=45;puffs.forEach(m=>m.visible=false);$('advancedpanel').hidden=false;say('ODMOWA DOSTĘPU / UKOŃCZONA','Misje ukończone · otwarty świat','Bejnar: Czekamy na kolejny plan.');}
 function retry(){reset();unlock();start();}
 addEventListener('keydown',e=>{if(e.code==='Escape'){held=false;hold=0;}});
 return{unlock,tick,reset,retry,restoreComplete,getState:()=>({stage,active:!['locked','ready','complete'].includes(stage),lootGB:loot*32,broken,nodes:[...nodes],load,heat,index,alert,advanced:[...advanced]})};
}
