export function createEpilogue(T,api,barn,allies,done){
 let stage='idle',held=false,hold=0,time=0,assets=[],drinks=[],bomb=null,flames=[],blast=null,crackle=0;
 const $=id=>document.getElementById(id),center={x:barn.x,z:barn.z},outside={x:barn.x,z:barn.z-23};
 const materials={};for(const key of ['explosion','fire']){const map=new T.TextureLoader().load('./textures/effects/'+key+'.png');if(map)map.colorSpace=T.SRGBColorSpace;materials[key]=new T.SpriteMaterial({...(map?{map}:{}),transparent:true,depthWrite:false,blending:T.AdditiveBlending,color:'#ffffff'});}
 const say=(goal,line)=>{$('missionobjective').textContent=goal;if(line)$('missiondialog').textContent=line;};
 function block(w,h,d,x,y,z,color,solid=false){const m=api.box(w,h,d,x,y,z,color,solid);assets.push(m);return m;}
 function bottle(ch){const group=new T.Group(),body=new T.Mesh(new T.CylinderGeometry(.06,.07,.23,6),api.surfaceMaterial('#526857','glass')),neck=new T.Mesh(new T.CylinderGeometry(.025,.025,.12,6),api.surfaceMaterial('#526857','glass'));neck.position.y=.17;group.add(body,neck);const hand=ch.limbs?.find(l=>l.arm&&l.side===-1)?.hand;if(hand)hand.add(group);drinks.push(group);return group;}
 function start(){reset();stage='party';time=0;const light=new T.PointLight('#ffd6a0',45,25,2);light.position.set(barn.x,3.8,barn.z);api.scene.add(light);assets.push(light);api.switchControl(allies[2],'MACIOSZEK',2);allies.forEach((ch,i)=>{if(i===2)return;ch.root.visible=true;const a=(i>2?i-1:i)*Math.PI/2,x=barn.x+Math.cos(a)*2.8,z=barn.z+Math.sin(a)*2.8;ch.root.position.set(x,0,z);ch.root.rotation.y=Math.atan2(barn.x-x,barn.z-z);const yaw=ch.root.rotation.y,part=(w,h,d,lx,y,lz)=>{const m=block(w,h,d,x+lx*Math.cos(yaw)+lz*Math.sin(yaw),y,z-lx*Math.sin(yaw)+lz*Math.cos(yaw),'#756b56',true);m.rotation.y=yaw;if(m.userData.obstacle){m.userData.obstacle.w=Math.abs(w*Math.cos(yaw))+Math.abs(d*Math.sin(yaw));m.userData.obstacle.d=Math.abs(w*Math.sin(yaw))+Math.abs(d*Math.cos(yaw));}return m;};part(1,.15,1,0,.55,0);part(1,1,.15,0,1,-.48);for(const lx of [-.4,.4])for(const lz of [-.4,.4])part(.12,.5,.12,lx,.25,lz);bottle(ch);});block(2,.12,1.5,barn.x-5,.9,barn.z-4,'#937553',true);for(const dx of [-.85,.85])for(const dz of [-.6,.6])block(.14,.85,.14,barn.x-5+dx,.425,barn.z-4+dz,'#937553',true);for(let i=0;i<4;i++)block(.12,.3,.12,barn.x-5+i*.25,1.1,barn.z-4,'#526857');api.toggleContent(assets,[],true);$('endingchoice').hidden=true;api.sound('party_cheer');say('F przy stole · weź butelkę i dołącz do imprezy. F w środku stodoły · podłóż bombę.','Bejnar: Siadaj z nami. Za Ekonom!');}
 function interaction(dt,p,target,label,duration,action){if(Math.hypot(p.x-target.x,p.z-target.z)<2.3&&!api.state().driving){$('missionprompt').textContent=label+' · '+Math.floor(hold/duration*100)+'%';hold=held?hold+dt:0;if(hold>=duration){hold=0;held=false;action();}}else hold=0;return target;}
 function reset(){for(const drink of drinks){drink.removeFromParent();drink.traverse(m=>m.geometry?.dispose());}drinks=[];api.toggleContent(assets,[],false);for(const asset of assets)asset.geometry?.dispose();assets=[];for(const f of flames){api.scene.remove(f);f.material.dispose();}flames=[];if(blast){api.scene.remove(blast);blast.material.dispose();}blast=null;for(const ch of allies){ch.body?.position.set(0,0,0);for(const l of ch.limbs||[]){l.upper.rotation.set(0,0,0);l.joint.rotation.set(0,0,0);}}api.loopSound?.('fire',0);stage='idle';held=false;hold=0;}
 function pose(ch,sitting,toast=false){if(!ch.body)return;ch.body.rotation.set(0,0,0);ch.body.position.y=sitting?-.55:0;for(const l of ch.limbs){l.upper.rotation.set(l.arm?(toast?-1.5:-.65):sitting?-1.4:0,0,l.arm?-l.side*.08:0);l.joint.rotation.set(l.arm?-.85:sitting?1.4:0,0,0);}}
 function detonate(){stage='line';time=0;api.sound('final_choice');say('Macioszek przygotowuje detonator.','Macioszek: To co panowie, wychodzimy na przerwę.');}
 function tick(dt){if(stage==='idle'||!api.active())return null;time+=dt;const p=api.state().position;$('missionprompt').textContent='';
  if(['party','join'].includes(stage))allies.forEach((ch,i)=>{if(i!==2)pose(ch,true);});
  if(stage==='party'){const drink={x:barn.x-5,z:barn.z-4};if(Math.hypot(p.x-drink.x,p.z-drink.z)<2.3)return interaction(dt,p,drink,'F · weź butelkę / Wspólne rządy',1,()=>{stage='join';time=0;bottle(allies[2]);api.sound('bottle_pickup');api.sound('drink');api.sound('toast');say('WSPÓLNE RZĄDY','Macioszek: Za rodzinę.');});return interaction(dt,p,center,'F · podłóż bombę / Jeden król',2,()=>{stage='toast';bomb=block(.55,.2,.4,barn.x,.2,barn.z,'#222a2e');block(.08,.04,.08,barn.x,.32,barn.z,'#ee3737');api.sound('bomb_plant');say('F · zawołaj wszystkich na toast w środku stodoły.');});}
  if(stage==='join'){pose(allies[2],false,true);if(time>5){reset();done('family');}return null;}
  if(stage==='toast')return interaction(dt,p,center,'F · zbierz ekipę na toast',1,()=>{stage='gather';time=0;api.sound('toast_call');say('Ekipa zbiera się przy bombie. Wyjdź przez przednie wejście.');});
  if(['gather','outside','line'].includes(stage)){let gathered=true;allies.forEach((ch,i)=>{if(i===2)return;const a=(i>2?i-1:i)*Math.PI/2,target={x:barn.x+Math.cos(a)*1.8,z:barn.z+Math.sin(a)*1.8},pos=ch.root.position,d=Math.hypot(pos.x-target.x,pos.z-target.z);if(d>.15){gathered=false;const step=Math.min(d,dt*1.6);pos.x+=(target.x-pos.x)/d*step;pos.z+=(target.z-pos.z)/d*step;api.animate?.(ch,dt,1.6,false,false);}else pose(ch,false,true);});if(stage==='gather'&&gathered){stage='outside';say('Wyjdź przed stodołę. F · wygłoś ostatni toast i zdetonuj.');}if(stage==='outside')return interaction(dt,p,outside,'F · ostatni toast / detonator',.5,detonate);if(stage==='gather')return outside;}
  if(stage==='line'&&time>Math.max(4,api.soundDuration?.('final_choice')||0)){stage='fire';time=0;api.sound('detonator');api.sound('explosion');api.destroyBarn();allies.forEach((ch,i)=>{if(i!==2)ch.root.visible=false;});blast=new T.Sprite(materials.explosion.clone());blast.position.set(barn.x,4,barn.z);blast.scale.set(32,24,1);api.scene.add(blast);for(let i=0;i<8;i++){const f=new T.Sprite(materials.fire.clone());f.position.set(barn.x-9+i%4*6,2,barn.z-5+Math.floor(i/4)*10);f.scale.set(6,7,1);api.scene.add(f);flames.push(f);}say('JEDEN KRÓL','Macioszek: Koniec zmiany.');}
  if(stage==='fire'){api.loopSound?.('fire',.65);crackle-=dt;if(crackle<=0){api.sound('fire_crackle');crackle=1.2;}if(blast){blast.material.opacity=Math.max(0,1-time/2);blast.scale.set(32+time*8,24+time*6,1);}flames.forEach((f,i)=>f.scale.set(6+Math.sin(time*8+i)*.3,7+Math.sin(time*11+i)*.6,1));if(time>8){reset();done('solo');}}return null;
 }
 addEventListener('keydown',e=>{if(e.code==='KeyF'&&api.active())held=true;});addEventListener('keyup',e=>{if(e.code==='KeyF')held=false;});addEventListener('blur',()=>held=false);$('interact').addEventListener('pointerdown',()=>held=true);for(const e of ['pointerup','pointercancel','pointerleave'])$('interact').addEventListener(e,()=>held=false);
 addEventListener('keydown',e=>{if(e.code==='Escape'){held=false;hold=0;}});
 return{start,tick,reset,getState:()=>({stage})};
}
