import {MAP} from './map-layout.js?v=roof-seat-2';
export function createMemoryMission(T,api,barn,sharedVan){
 const $=id=>document.getElementById(id),site=MAP.locations.police;let stage='locked',timer=0,hold=0,held=false,count=0,loot=0,health=100,cooldown=0,transition=0,routeIndex=0,tech=[],content=[],roads=[],guards=[],bound=[],blackout=false;
 let exitGate,homeContent=[],fans=[];let van,travelVehicle,door,drill,windowLights=[],security=[],smoke=[],racks=[],students=[],tablet,crowbar,maskProps=[],serverLight;
 const outbound=[[barn.x,950],[-300,950],[-300,-350],[-350,-350],[-350,-650],[site.x,-650],[site.x,site.z+45]],inbound=[...outbound.slice(0,-1)].reverse().concat([[barn.x,barn.z-30]]);
 const text=(heading,goal,line)=>{$('missiontitle').textContent=heading;$('missionobjective').textContent=goal;$('missiondialog').textContent=line;$('missionprompt').textContent='';$('mission').hidden=false;};
 function build(){
  const before=new Set(api.scene.children);const box=api.box;
  box(38,.08,70,site.x,.03,site.z,'#3b454c');box(.4,5,70,site.x-19,2.5,site.z,'#59616a',true);box(.4,5,70,site.x+19,2.5,site.z,'#59616a',true);box(38,5,.4,site.x,2.5,site.z-35,'#59616a',true);
  for(const x of [site.x-12,site.x+12])box(14,5,.4,x,2.5,site.z+35,'#59616a',true);
  for(const x of [site.x-12,site.x+12])box(14,5,.4,x,2.5,site.z-5,'#505b64',true);
  box(39,.4,71,site.x,5.2,site.z,'#59616a',true);box(10,2,.4,site.x,4,site.z+35,'#59616a',true);box(10,2,.4,site.x,4,site.z-5,'#505b64',true);
  door=box(10,3,.3,site.x,1.5,site.z-5,'#697580',true);drill=box(.25,.35,1,site.x,1.2,site.z-3.8,'#c5a154');drill.visible=false;
  for(let i=0;i<6;i++){const x=site.x+(i%2?-13:13),z=site.z+8+Math.floor(i/2)*7;box(4,.25,2,x,1,z,'#776b5c',true);box(1.5,2.2,1.2,x,1.1,z+2,'#5d6d77',true);}
  for(let i=0;i<6;i++){const x=site.x-12+(i%3)*12,z=site.z-16-Math.floor(i/3)*10;const rack=box(3,2.8,2,x,1.4,z,'#1d2c36',true);racks.push({mesh:rack,x,z:z+2.5,opened:false,remaining:12});for(let j=0;j<6;j++)box(2.7,.06,.03,x,.3+j*.4,z+1.02,'#9ba9ae');}
  for(let i=0;i<5;i++){const light=new T.PointLight('#d4e9ff',24,25,2);light.position.set(site.x,3,site.z-25+i*13);api.scene.add(light);windowLights.push(light);}
  for(const x of [site.x-17,site.x+17]){const camera=box(.4,.3,.6,x,3.8,site.z+29,'#1b252d');security.push(camera);}
  const sign=api.sign('KOMENDA / ZAPLECZE',14,1.3);sign.position.set(site.x,4,site.z+35.3);api.scene.add(sign);
  exitGate=box(12,.15,.2,site.x,1.1,site.z+49,'#dadada');van=sharedVan;if(!van)throw new Error('Misja 2 wymaga istniejącego vana ekipy.');
  // The forecourt uses the permanent road surface; no coplanar mission overlay.
  for(let i=0;i<2;i++){const ch=api.character({shirt:i?'#606877':'#3c4752',pants:'#252b33',skin:'#c99e7b',hair:'#2e2925'});students.push(ch);ch.root.visible=false;}
  const prop=(w,h,d,color,ch,x,y,z)=>{const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color}));m.position.set(x,y,z);ch.body.add(m);return m;};
  tablet=prop(.48,.3,.04,'#607c9b',api.chars[2],0,1.4,.35);crowbar=prop(.06,.65,.06,'#8b9298',students[0],.55,1.2,.1);prop(.2,.07,.15,'#d6d7d0',students[0],-.54,1.1,.1);
  for(const ch of [...api.chars,...students]){const mask=prop(.54,.5,.5,'#111820',ch,0,2.18,0);mask.visible=false;maskProps.push(mask);const eyes=prop(.32,.065,.025,'#b1a58b',ch,0,2.21,.263);mask.add(eyes);eyes.position.set(0,.03,.263);}
  for(let i=0;i<12;i++){const puff=new T.Mesh(new T.IcosahedronGeometry(.8,0),new T.MeshBasicMaterial({color:'#a4adb3',transparent:true,opacity:.5,depthWrite:false}));puff.position.set(site.x+(i%3-1)*3,1+(i%4)*.5,site.z+12+Math.floor(i/3)*3);puff.visible=false;api.scene.add(puff);smoke.push(puff);}
  content=api.scene.children.filter(m=>!before.has(m));api.toggleContent?.(content,roads,true);
 }
 function control(ch,label,index=-1){api.switchControl?.(ch,label,index);api.holster();}
 function move(x,z){api.teleport(x,z);}
 function activate(){if(stage!=='ready')return;if(!van)build();else{api.toggleContent?.(content,roads,true);windowLights.forEach(l=>{l.color.set('#d4e9ff');l.intensity=24;});security.forEach(m=>m.visible=true);racks.forEach(r=>{r.opened=false;r.remaining=12;});door.visible=true;api.toggleContent?.([door],[],true);drill.visible=false;exitGate.visible=true;tablet.visible=true;smoke.forEach(m=>m.visible=false);}stage=api.hasWeapon&&!api.hasWeapon(1)?'purchase':'travel';api.grantMissionMoney?.('mission2-rifle',900);routeIndex=0;timer=0;hold=0;loot=0;count=0;health=100;travelVehicle=van;const startPosition=api.state().position;routeIndex=outbound.reduce((best,point,i)=>Math.hypot(startPosition.x-point[0],startPosition.z-point[1])<Math.hypot(startPosition.x-outbound[best][0],startPosition.z-outbound[best][1])?i:best,0);control(api.chars[2],'MACIOSZEK',2);
  if(stage==='purchase'){text('MISJA 2 / UZBROJENIE','Jedź do sklepu z bronią w centrum. Wysiądź, podejdź do wejścia i naciśnij F. Kup karabin za $900.','Bejnar: Masz $900 na podstawowy karabin. Kup go, zanim ruszymy na komendę.');return;}
  text('MISJA 2 / OPERACJA PAMIĘĆ OPERACYJNA','E · wsiądź do dowolnego pojazdu. Jedź do komendy za znacznikiem.','Bejnar: Masz już karabin, więc jesteśmy uzbrojeni. Ruszamy po RAM. Macioszek: Zajmę się zasilaniem.');}
 function spawnWave(amount){for(let i=0;i<amount;i++){const ch=api.character({shirt:'#263e5a',pants:'#1c2632',skin:'#c99e7b',hair:'#222e3a'});ch.root.position.set(site.x-8+i*8,0,site.z+30);const ped={ch,health:100,deadTime:999,prologue:true,meshes:[],color:'#263e5a'};ch.root.traverse(m=>{if(m.isMesh){ped.meshes.push(m);m.userData.pedestrian=ped;}});guards.push(ped);api.pedestrians.push(ped);}}
 function clearGuards(){for(const p of guards){api.scene.remove(p.ch.root);if(p.rag)api.scene.remove(p.rag.group);const i=api.pedestrians.indexOf(p);if(i>=0)api.pedestrians.splice(i,1);}guards=[];}
 function assault(){api.sound?.('door_breach');stage='assault';timer=0;hold=0;blackout=true;windowLights.forEach(l=>l.intensity=0);security.forEach(m=>m.visible=false);maskProps.forEach(m=>m.visible=true);tablet.visible=false;control(students[0],'PIERWSZA PE');spawnWave(3);text('02 / ZABEZPIECZENIE TERENU','Podejdź do 3 zdezorientowanych oficerów i przytrzymaj F, aby ich związać.','Bejnar: Kamery i zamki nie działają. Wejście techniczne jest otwarte.');}
 function beginDrill(){stage='drill';timer=0;hold=0;health=100;drill.visible=true;api.equipRifle();api.chars[0].root.position.set(site.x+1,0,site.z-3);windowLights.forEach(l=>{l.color.set('#ff6041');l.intensity=18;});spawnWave(3);text('03 / WIERTŁO','Broń Bystreka przez 30 sekund. LPM · strzał, R · przeładuj.','Bystrek: Wiercę zamek. Bejnar: Zasilanie awaryjne! Trzymaj korytarz!');}
 function beginLoot(){stage='loot';timer=0;hold=0;door.visible=false;api.toggleContent?.([door],[],false);drill.visible=false;control(students[1],'DRUGA PE');clearGuards();text('04 / KRADZIEŻ MOCY','45 sekund do posiłków. F: otwórz szafę. Klikaj LPM w zielonym oknie, aby wyjąć RAM.','Macioszek: Radiowozy zjeżdżają się z całego miasta. Nie traćcie czasu!');$('loottiming').hidden=false;}
 function lootClick(){if(stage!=='loot'||!api.active()||cooldown>0)return;const p=api.state().position,r=racks.find(r=>r.opened&&r.remaining>0&&Math.hypot(p.x-r.x,p.z-r.z)<3);if(!r)return;cooldown=.22;const phase=(Math.sin(timer*4)+1)/2;if(phase>=.28&&phase<=.72){r.remaining--;loot++;$('missiondialog').textContent='DDR5 zabezpieczone · '+loot*32+' GB w torbie';}else $('missiondialog').textContent='Poczekaj na zielone okno — liczy się precyzja.';}
 function retreat(){stage='retreat';timer=0;hold=0;api.holster();$('loottiming').hidden=true;smoke.forEach(m=>m.visible=true);control(students[1],'DRUGA PE');text('05 / TAKTYCZNY ODWROT','Wróć do dowolnego pojazdu i przytrzymaj F, aby załadować torbę.','Bejnar: Osłaniam tyły. Macioszek: Dym w korytarzu! Do wyjścia!');}
 function returnHome(){stage='install';timer=0;hold=0;api.toggleContent?.(content.filter(m=>m!==van.root),roads,false);for(const m of [...maskProps,tablet,crowbar])m.visible=false;students.forEach(ch=>ch.root.visible=false);control(api.chars[0],'BYSTREK',0);api.chars[1].root.position.set(barn.x+2,0,barn.z-1);api.chars[2].root.position.set(barn.x-6,0,barn.z-2);
  const beforeHome=new Set(api.scene.children);const trough=api.box(3,.5,1.3,barn.x-9,.4,barn.z-4,'#6d6859');const board=api.box(2.7,.08,1,barn.x-9,.7,barn.z-4,'#446c48');for(let i=0;i<Math.min(loot,12);i++)api.box(.09,.15,.7,barn.x-10+i*.17,.81,barn.z-4,'#5ea761');
  serverLight=new T.PointLight('#5efb78',0,18,2);serverLight.position.set(barn.x-9,2,barn.z-4);api.scene.add(serverLight);for(let i=0;i<2;i++){const fan=new T.Mesh(new T.BoxGeometry(1,.1,.1),new T.MeshStandardMaterial({color:'#8b989e'}));fan.position.set(barn.x-9+i*1.5,1.6,barn.z-3);api.scene.add(fan);fans.push(fan);}homeContent=api.scene.children.filter(m=>!beforeHome.has(m));text('06 / INSTALACJA W NOWYM DOMU','Przytrzymaj F przy korycie: zainstaluj RAM i uruchom serwerownię.','Macioszek: Płyta gotowa. Bystrek: Wiatraki już chłodzą. Włączamy.');}
 function complete(){stage='complete';api.missionComplete?.(2);serverLight.intensity=30;document.querySelector?.('#paused section')?.append?.($('techpanel')); $('techpanel').hidden=false;$('techbalance').textContent='RAM: '+loot*32+' GB';text('OPERACJA PAMIĘĆ OPERACYJNA / UKOŃCZONA',loot*32+' GB zdobyte · Esc: drzewko technologiczne','Bejnar: Teraz mamy moc. Następny plan: Piastowska.');}
 const distance=(p,x,z)=>Math.hypot(p.x-x,p.z-z);
 function interaction(dt,p,x,z,message,seconds,done){if(distance(p,x,z)<2.8&&!api.state().driving){$('missionprompt').textContent=message+(hold?' · '+Math.floor(hold/seconds*100)+'%':'');hold=held?hold+dt:0;if(hold>=seconds){hold=0;held=false;done();}}else hold=0;return{x,z};}
 function tick(dt){if(!api.active()||stage==='locked')return null;timer+=dt;cooldown=Math.max(0,cooldown-dt);for(const fan of fans)if(stage==='complete')fan.rotation.z+=dt*14;const p=api.state().position;$('missionprompt').textContent='';let target=null;
  if(stage==='ready'){const b=api.chars[1].root.position;target=interaction(dt,p,b.x,b.z,'F · porozmawiaj z Bejnarem: Operacja Pamięć Operacyjna',1,activate);}
  else if(stage==='purchase'){target=api.gunShopLocation;if(api.hasWeapon(1)){stage='travel';const q=api.state().position;routeIndex=outbound.reduce((best,v,i)=>distance(q,...v)<distance(q,...outbound[best])?i:best,0);text('MISJA 2 / KOMENDA','Jedź do komendy dowolnym pojazdem za znacznikiem.','Bejnar: Karabin kupiony. Teraz po policyjny RAM!');}}
  else if(stage==='hack')target=interaction(dt,p,site.x,site.z+39,'F · tablet: odetnij zasilanie',3,assault);
  else if(stage==='assault'){const g=guards.find(g=>g.health>0);if(g){target=interaction(dt,p,g.ch.root.position.x,g.ch.root.position.z,'F · obezwładnij i zwiąż oficera',1,()=>{g.health=0;g.ch.root.rotation.x=-.25;bound.push(g.ch);count++;});$('missionobjective').textContent='Zabezpiecz parter · '+count+' / 3';}else target=interaction(dt,p,site.x,site.z-2,'F · zamontuj wiertło przy stalowych drzwiach',2,beginDrill);}
  else if(stage==='drill'){
   drill.rotation.z=timer*18;target={x:site.x,z:site.z-2};if(Math.floor((timer-dt)/10)<Math.floor(timer/10)&&timer<29)spawnWave(3);
   for(const g of guards)if(g.health>0){api.enemyAttack?.(g.ch,dt);const q=g.ch.root.position,d=distance(p,q.x,q.z);if(d>3){q.x+=(p.x-q.x)/d*dt*1.2;q.z+=(p.z-q.z)/d*dt*1.2;api.animate?.(g.ch,dt,1.2,false,false);}else health-=dt*5;}
   $('missionobjective').textContent='Zamek: '+Math.min(100,Math.floor(timer/30*100))+'% · osłona '+Math.ceil(health)+'%';
   if(health<=0){if(api.fail){api.fail('Funkcjonariusze przerwali wiercenie.');return;}clearGuards();timer=0;health=100;move(site.x,site.z);spawnWave(3);$('missiondialog').textContent='Punkt kontrolny: broń wiertła, korzystaj z osłon.';}if(timer>=30)beginLoot();
  }else if(stage==='loot'){
   const phase=(Math.sin(timer*4)+1)/2;$('lootcursor').style.left=(phase*100)+'%';$('reinforcements').value=timer;const r=racks.find(r=>r.remaining>0&&distance(p,r.x,r.z)<3)||racks.find(r=>r.remaining>0);if(r){target={x:r.x,z:r.z};if(!r.opened)target=interaction(dt,p,r.x,r.z,'F · otwórz obudowę serwera',.8,()=>r.opened=true);else if(distance(p,r.x,r.z)<3)$('missionprompt').textContent='LPM · wyjmij RAM, gdy wskaźnik jest w zielonym polu';}
   $('missionobjective').textContent='Posiłki za '+Math.ceil(45-timer)+' s · '+loot*32+' GB DDR5';if(timer>=45){if(loot===0){if(api.fail){api.fail('Posiłki dotarły przed zdobyciem RAM-u.');return;}timer=0;$('missiondialog').textContent='Nie zebrano RAM-u. Powtórka od punktu kontrolnego w serwerowni.';}else retreat();}
  }else if(stage==='retreat'){const car=api.nearestVehicle?.()||travelVehicle||van;const rear=(car.halfLength||3.8)+.7;target=interaction(dt,p,car.x-Math.sin(car.yaw||0)*rear,car.z-Math.cos(car.yaw||0)*rear,'F · załaduj RAM do pojazdu i wycofaj ekipę',2,()=>{travelVehicle=car;stage='departure';routeIndex=0;timer=0;api.holster();exitGate.visible=false;text('05 / POWRÓT DO STODOŁY','E · dowolny pojazd. Odwieź RAM do bazy za znacznikiem.','Bejnar: Torby załadowane. Macioszek: Wracamy do stodoły!');});smoke.forEach((m,i)=>{m.scale.setScalar(1.3+Math.sin(timer+i)*.2);});}
  else if(stage==='departure'||stage==='travel'){
   const path=stage==='travel'?outbound:inbound,point=path.at(-1);target={x:point[0],z:point[1]};
   if(api.state().driving){travelVehicle=api.state().driving;}
   if(!api.state().driving){const car=api.nearestVehicle?.()||travelVehicle;target={x:car.x,z:car.z};}
   const arrived=distance(travelVehicle,...path.at(-1))<10;
   $('missionobjective').textContent=(stage==='travel'?'Jedź do komendy':'Odwieź RAM do stodoły')+' · jedź dowolną trasą';
   if(arrived){$('missionprompt').textContent='Zatrzymaj pojazd i wysiądź: E';if(!api.state().driving&&distance(p,travelVehicle.x,travelVehicle.z)<12){if(stage==='travel'){stage='hack';text('01 / ODCIĘCIE ZASILANIA','F przy zapleczu: odetnij zasilanie.','Macioszek: Jesteśmy na miejscu. Czas odłączyć prąd.');}else returnHome();}}
  }
  else if(stage==='install')target=interaction(dt,p,barn.x-9,barn.z-5,'F · zamontuj RAM i wciśnij zasilanie',3,complete);
  return target;
 }
 function unlock(){stage='ready';text('NOWA MISJA / BEJNAR','Porozmawiaj z Bejnarem w stodole. F · rozmowa.','Bejnar: Mam pomysł na rozbudowę naszej serwerowni.');}
 function reset(){clearGuards();api.toggleContent?.(homeContent,[],false);homeContent=[];fans=[];tech=[];loot=0;api.upgrade?.('reset');for(const [id,label] of [['techreload','Sprzęt: szybsze przeładowanie · 32 GB'],['techvan','Van: mocniejszy napęd · 64 GB'],['techplan','Plan ataku na Piastowską · wymaga sprzętu']]){$(id).disabled=false;$(id).textContent=label;}api.toggleContent?.(content,roads,false);for(const m of [...maskProps,tablet,crowbar])if(m)m.visible=false;students.forEach(c=>c.root.visible=false);stage='locked';held=false;hold=0;$('techpanel').hidden=true;$('loottiming').hidden=true;}
 for(const [id,key,cost] of [['techreload','reload',32],['techvan','van',64],['techplan','plan',0]])$(id).onclick=()=>{if(stage!=='complete'||tech.includes(key))return;if(key==='plan'&&!tech.includes('reload')){$('techbalance').textContent='Najpierw odblokuj sprzęt.';return;}if(loot*32<cost){$('techbalance').textContent='Za mało RAM-u.';return;}loot-=cost/32;tech.push(key);api.upgrade?.(key);$(id).disabled=true;$(id).textContent+=' ✓';$('techbalance').textContent='RAM: '+loot*32+' GB';};
 addEventListener('keydown',e=>{if(e.code==='KeyF'&&api.active())held=true;});addEventListener('keyup',e=>{if(e.code==='KeyF')held=false;});addEventListener('blur',()=>held=false);
 $('interact').addEventListener('pointerdown',()=>held=true);for(const event of ['pointerup','pointercancel','pointerleave'])$('interact').addEventListener(event,()=>held=false);
 $('world').addEventListener('pointerdown',e=>{if(e.button===0)lootClick();});$('lootbutton').onclick=lootClick;
 function retry(){reset();unlock();activate();}
 function restoreComplete(){stage='complete';loot=4;text('OPERACJA PAMIĘĆ OPERACYJNA / UKOŃCZONA','Rozdział przywrócony · Bejnar ma kolejny plan.','Serwerownia gotowa na uderzenie na Piastowską.');}
 addEventListener('keydown',e=>{if(e.code==='Escape'){held=false;hold=0;}});
 return{unlock,tick,reset,retry,restoreComplete,getState:()=>({stage,lootGB:loot*32,count,blackout,tech:[...tech],active:!['locked','ready','complete'].includes(stage)})};
}
